const BRAND_PRIMARY = '#18bcc5'
const BRAND_PRIMARY_STRONG = '#12aab3'
const BRAND_PRIMARY_LIGHT = '#59d2d7'
const BRAND_PRIMARY_SOFT = '#e8f8f9'
const BRAND_PRIMARY_SOFT_STRONG = '#d8f2f4'

module.exports = {
  BRAND_PRIMARY,
  BRAND_PRIMARY_STRONG,
  BRAND_PRIMARY_LIGHT,
  BRAND_PRIMARY_SOFT,
  BRAND_PRIMARY_SOFT_STRONG
}
