CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) NOT NULL,
  openid VARCHAR(128) NOT NULL,
  nickname VARCHAR(100) DEFAULT '',
  avatar_url VARCHAR(1024) DEFAULT '',
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_openid (openid)
);
