CREATE TABLE IF NOT EXISTS courses (
  id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  course_category VARCHAR(20) DEFAULT '体适能',
  cover VARCHAR(1024) DEFAULT '',
  images TEXT,
  description TEXT,
  age_limit VARCHAR(100) DEFAULT '',
  address VARCHAR(255) DEFAULT '',
  location_district VARCHAR(100) DEFAULT '',
  location_community VARCHAR(100) DEFAULT '',
  location_detail VARCHAR(255) DEFAULT '',
  longitude DECIMAL(10,6) NULL,
  latitude DECIMAL(10,6) NULL,
  group_price INT DEFAULT 0,
  original_price INT DEFAULT 0,
  publish_time DATETIME NULL,
  unpublish_time DATETIME NULL,
  deadline DATETIME NULL,
  start_time DATETIME NULL,
  end_time DATETIME NULL,
  default_target_count INT NULL,
  max_groups INT DEFAULT 0,
  status INT DEFAULT 0,
  coach_name VARCHAR(100) DEFAULT '',
  coach_intro TEXT,
  coach_certificates TEXT,
  rules TEXT,
  insurance_desc TEXT,
  service_qr_code VARCHAR(1024) DEFAULT '',
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `groups` (
  id VARCHAR(36) NOT NULL,
  course_id VARCHAR(36) NOT NULL,
  creator_id VARCHAR(36) NULL,
  status VARCHAR(20) DEFAULT 'active',
  current_count INT DEFAULT 0,
  target_count INT DEFAULT 0,
  expire_time DATETIME NULL,
  created_at DATETIME NULL,
  success_time DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_groups_course_id (course_id),
  KEY idx_groups_status (status),
  KEY idx_groups_expire_time (expire_time)
);

CREATE TABLE IF NOT EXISTS group_members (
  group_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  joined_at DATETIME NULL,
  PRIMARY KEY (group_id, user_id),
  KEY idx_group_members_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(36) NOT NULL,
  order_no VARCHAR(32) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  course_id VARCHAR(36) NOT NULL,
  group_id VARCHAR(36) NULL,
  amount INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'pending',
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  pay_time DATETIME NULL,
  refund_time DATETIME NULL,
  refund_reason TEXT,
  refund_operator_id VARCHAR(36) NULL,
  transaction_id VARCHAR(64) DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY uniq_orders_order_no (order_no),
  KEY idx_orders_user_id (user_id),
  KEY idx_orders_course_id (course_id),
  KEY idx_orders_group_id (group_id),
  KEY idx_orders_status (status)
);

CREATE TABLE IF NOT EXISTS payment_records (
  id VARCHAR(36) NOT NULL,
  order_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  course_id VARCHAR(36) NOT NULL,
  group_id VARCHAR(36) NULL,
  provider VARCHAR(20) DEFAULT 'wechat',
  channel VARCHAR(30) DEFAULT 'mini_program',
  payment_mode VARCHAR(20) DEFAULT 'mock',
  out_trade_no VARCHAR(64) NOT NULL,
  transaction_id VARCHAR(64) DEFAULT '',
  amount INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'pending',
  callback_status VARCHAR(32) DEFAULT '',
  prepare_payload TEXT,
  callback_payload TEXT,
  paid_at DATETIME NULL,
  closed_at DATETIME NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_payment_records_order_id (order_id),
  UNIQUE KEY uniq_payment_records_out_trade_no (out_trade_no)
);
