-- 课包拼团回归种子数据
-- 覆盖场景：
-- 1. 一个可开团课包（无团、无订单）
-- 2. 一个进行中团
-- 3. 一个已成团团
-- 4. 一个已失败团（订单已退款）

INSERT INTO `users` (
  id,
  openid,
  nickname,
  avatar_url,
  created_at,
  updated_at
) VALUES
  (
    'user_pkg_seed_001',
    'seed_pkg_u01',
    '课包测试家长01',
    'https://dummyimage.com/120x120/ffd6a5/6b3f1d.png&text=PKG01',
    NOW(),
    NOW()
  ),
  (
    'user_pkg_seed_002',
    'seed_pkg_u02',
    '课包测试家长02',
    'https://dummyimage.com/120x120/caffbf/245b3b.png&text=PKG02',
    NOW(),
    NOW()
  ),
  (
    'user_pkg_seed_003',
    'seed_pkg_u03',
    '课包测试家长03',
    'https://dummyimage.com/120x120/9bf6ff/1e5162.png&text=PKG03',
    NOW(),
    NOW()
  ),
  (
    'user_pkg_seed_004',
    'seed_pkg_u04',
    '课包测试家长04',
    'https://dummyimage.com/120x120/bdb2ff/3f2a74.png&text=PKG04',
    NOW(),
    NOW()
  ),
  (
    'user_pkg_seed_005',
    'seed_pkg_u05',
    '课包测试家长05',
    'https://dummyimage.com/120x120/ffafcc/742d48.png&text=PKG05',
    NOW(),
    NOW()
  ),
  (
    'user_pkg_seed_006',
    'seed_pkg_u06',
    '课包测试家长06',
    'https://dummyimage.com/120x120/a0c4ff/24456b.png&text=PKG06',
    NOW(),
    NOW()
  )
ON DUPLICATE KEY UPDATE
  openid = VALUES(openid),
  nickname = VALUES(nickname),
  avatar_url = VALUES(avatar_url),
  updated_at = VALUES(updated_at);

DELETE FROM `orders`
WHERE id IN (
  'pkg_order_seed_001',
  'pkg_order_seed_002',
  'pkg_order_seed_003',
  'pkg_order_seed_004',
  'pkg_order_seed_005',
  'pkg_order_seed_006',
  'pkg_order_seed_007',
  'pkg_order_seed_008'
)
   OR package_id IN (
     'package_seed_open_001',
     'package_seed_active_002',
     'package_seed_success_003',
     'package_seed_failed_004'
   );

DELETE FROM `payment_records`
WHERE id IN (
  'pkg_pay_seed_001',
  'pkg_pay_seed_002',
  'pkg_pay_seed_003',
  'pkg_pay_seed_004',
  'pkg_pay_seed_005',
  'pkg_pay_seed_006',
  'pkg_pay_seed_007',
  'pkg_pay_seed_008'
)
   OR order_id IN (
     'pkg_order_seed_001',
     'pkg_order_seed_002',
     'pkg_order_seed_003',
     'pkg_order_seed_004',
     'pkg_order_seed_005',
     'pkg_order_seed_006',
     'pkg_order_seed_007',
     'pkg_order_seed_008'
   )
   OR package_id IN (
     'package_seed_open_001',
     'package_seed_active_002',
     'package_seed_success_003',
     'package_seed_failed_004'
   );

DELETE FROM `package_groups`
WHERE id IN (
  'pkg_group_seed_001',
  'pkg_group_seed_002',
  'pkg_group_seed_003'
)
   OR package_id IN (
     'package_seed_open_001',
     'package_seed_active_002',
     'package_seed_success_003',
     'package_seed_failed_004'
   );

INSERT INTO `course_packages` (
  id,
  name,
  cover,
  images,
  total_price,
  package_category,
  age_range,
  supported_people,
  location_district,
  location_community,
  location_detail,
  longitude,
  latitude,
  coach_name,
  coach_intro,
  coach_certificates,
  description,
  deadline_hours,
  status,
  created_at,
  updated_at,
  created_by,
  updated_by
) VALUES
  (
    'package_seed_open_001',
    '[课包回归] 可开团周末体适能 5 次课',
    'https://dummyimage.com/960x540/e8f4ff/21598a.png&text=Package+Open',
    '[\"https://dummyimage.com/1280x720/e8f4ff/21598a.png&text=Package+Open+01\",\"https://dummyimage.com/1280x720/d5ebff/21598a.png&text=Package+Open+02\"]',
    159900,
    '体适能',
    '4-8岁',
    '2,4,6',
    '南山区',
    '科技园社区',
    '科技园邻动训练点 A 场',
    113.9512000,
    22.5431000,
    '课包教练 A',
    '用于验证“立即开团”链路的课包种子。',
    '[\"https://dummyimage.com/480x320/e8f4ff/21598a.png&text=Package+Coach+A\"]',
    '<p>当前课包用于验证首页、详情页和开团页，不预置任何进行中的团。</p>',
    48,
    1,
    NOW(),
    NOW(),
    NULL,
    NULL
  ),
  (
    'package_seed_active_002',
    '[课包回归] 进行中少儿体适能 5 次课',
    'https://dummyimage.com/960x540/fff3de/8a5a12.png&text=Package+Active',
    '[\"https://dummyimage.com/1280x720/fff3de/8a5a12.png&text=Package+Active+01\",\"https://dummyimage.com/1280x720/ffe7c7/8a5a12.png&text=Package+Active+02\"]',
    198000,
    '体适能',
    '5-9岁',
    '2,4,6,8',
    '福田区',
    '香蜜社区',
    '香蜜公园邻动训练区 2 号草坪',
    114.0417000,
    22.5498000,
    '课包教练 B',
    '用于验证“去参团”与进行中团详情。',
    '[\"https://dummyimage.com/480x320/fff3de/8a5a12.png&text=Package+Coach+B\"]',
    '<p>当前课包预置一个仍在招募中的 4 人团，可直接验证参团流程。</p>',
    48,
    1,
    NOW(),
    NOW(),
    NULL,
    NULL
  ),
  (
    'package_seed_success_003',
    '[课包回归] 已成团平衡训练 5 次课',
    'https://dummyimage.com/960x540/e7ffe9/1c7f3d.png&text=Package+Success',
    '[\"https://dummyimage.com/1280x720/e7ffe9/1c7f3d.png&text=Package+Success+01\",\"https://dummyimage.com/1280x720/d2f7da/1c7f3d.png&text=Package+Success+02\"]',
    256000,
    '体适能',
    '6-10岁',
    '2,4,8',
    '宝安区',
    '西乡社区',
    '西乡体育中心功能房',
    113.8824000,
    22.5731000,
    '课包教练 C',
    '用于验证已成团后的时间展示。',
    '[\"https://dummyimage.com/480x320/e7ffe9/1c7f3d.png&text=Package+Coach+C\"]',
    '<p>当前课包预置一个已成团团，可直接查看具体 5 次课时间。</p>',
    48,
    1,
    NOW(),
    NOW(),
    NULL,
    NULL
  ),
  (
    'package_seed_failed_004',
    '[课包回归] 已失败敏捷训练 5 次课',
    'https://dummyimage.com/960x540/ffe8e8/9a2c2c.png&text=Package+Failed',
    '[\"https://dummyimage.com/1280x720/ffe8e8/9a2c2c.png&text=Package+Failed+01\",\"https://dummyimage.com/1280x720/ffd5d5/9a2c2c.png&text=Package+Failed+02\"]',
    168800,
    '体适能',
    '4-8岁',
    '2,4',
    '龙华区',
    '民治社区',
    '民治会所多功能活动室',
    114.0446000,
    22.6213000,
    '课包教练 D',
    '用于验证失败退款结果页。',
    '[\"https://dummyimage.com/480x320/ffe8e8/9a2c2c.png&text=Package+Coach+D\"]',
    '<p>当前课包预置一个已失败团，订单已退款，可用于后台订单与详情页回归。</p>',
    48,
    1,
    NOW(),
    NOW(),
    NULL,
    NULL
  )
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  cover = VALUES(cover),
  images = VALUES(images),
  total_price = VALUES(total_price),
  package_category = VALUES(package_category),
  age_range = VALUES(age_range),
  supported_people = VALUES(supported_people),
  location_district = VALUES(location_district),
  location_community = VALUES(location_community),
  location_detail = VALUES(location_detail),
  longitude = VALUES(longitude),
  latitude = VALUES(latitude),
  coach_name = VALUES(coach_name),
  coach_intro = VALUES(coach_intro),
  coach_certificates = VALUES(coach_certificates),
  description = VALUES(description),
  deadline_hours = VALUES(deadline_hours),
  status = VALUES(status),
  updated_at = VALUES(updated_at),
  created_by = VALUES(created_by),
  updated_by = VALUES(updated_by);

INSERT INTO `package_groups` (
  id,
  package_id,
  creator_id,
  target_count,
  current_count,
  status,
  weekday,
  hour,
  first_class_time,
  deadline,
  created_at,
  success_time
) VALUES
  (
    'pkg_group_seed_001',
    'package_seed_active_002',
    'user_pkg_seed_001',
    4,
    2,
    'active',
    6,
    10,
    NULL,
    DATE_ADD(NOW(), INTERVAL 30 HOUR),
    DATE_SUB(NOW(), INTERVAL 18 HOUR),
    NULL
  ),
  (
    'pkg_group_seed_002',
    'package_seed_success_003',
    'user_pkg_seed_003',
    4,
    4,
    'success',
    3,
    18,
    DATE_ADD(DATE_ADD(DATE(NOW()), INTERVAL 7 DAY), INTERVAL 18 HOUR),
    DATE_ADD(NOW(), INTERVAL 24 HOUR),
    DATE_SUB(NOW(), INTERVAL 36 HOUR),
    DATE_SUB(NOW(), INTERVAL 12 HOUR)
  ),
  (
    'pkg_group_seed_003',
    'package_seed_failed_004',
    'user_pkg_seed_005',
    4,
    2,
    'failed',
    7,
    9,
    DATE_ADD(DATE_ADD(DATE(NOW()), INTERVAL 6 DAY), INTERVAL 9 HOUR),
    DATE_SUB(NOW(), INTERVAL 2 HOUR),
    DATE_SUB(NOW(), INTERVAL 72 HOUR),
    NULL
  );

INSERT INTO `orders` (
  id,
  order_no,
  user_id,
  order_type,
  course_id,
  group_id,
  package_id,
  package_group_id,
  package_action,
  package_context,
  amount,
  status,
  created_at,
  updated_at,
  pay_time,
  refund_time,
  refund_reason,
  refund_operator_id,
  transaction_id
) VALUES
  (
    'pkg_order_seed_001',
    'LDPKG20260419001',
    'user_pkg_seed_001',
    2,
    NULL,
    NULL,
    'package_seed_active_002',
    'pkg_group_seed_001',
    'start',
    '{\"targetCount\":4,\"weekday\":6,\"hour\":10}',
    49500,
    'success',
    DATE_SUB(NOW(), INTERVAL 18 HOUR),
    DATE_SUB(NOW(), INTERVAL 17 HOUR),
    DATE_SUB(NOW(), INTERVAL 17 HOUR),
    NULL,
    '',
    NULL,
    'TXN_PKG_ACTIVE_001'
  ),
  (
    'pkg_order_seed_002',
    'LDPKG20260419002',
    'user_pkg_seed_002',
    2,
    NULL,
    NULL,
    'package_seed_active_002',
    'pkg_group_seed_001',
    'join',
    NULL,
    49500,
    'success',
    DATE_SUB(NOW(), INTERVAL 12 HOUR),
    DATE_SUB(NOW(), INTERVAL 11 HOUR),
    DATE_SUB(NOW(), INTERVAL 11 HOUR),
    NULL,
    '',
    NULL,
    'TXN_PKG_ACTIVE_002'
  ),
  (
    'pkg_order_seed_003',
    'LDPKG20260419003',
    'user_pkg_seed_003',
    2,
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'start',
    '{\"targetCount\":4,\"weekday\":3,\"hour\":18}',
    64000,
    'success',
    DATE_SUB(NOW(), INTERVAL 36 HOUR),
    DATE_SUB(NOW(), INTERVAL 35 HOUR),
    DATE_SUB(NOW(), INTERVAL 35 HOUR),
    NULL,
    '',
    NULL,
    'TXN_PKG_SUCCESS_001'
  ),
  (
    'pkg_order_seed_004',
    'LDPKG20260419004',
    'user_pkg_seed_004',
    2,
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'join',
    NULL,
    64000,
    'success',
    DATE_SUB(NOW(), INTERVAL 30 HOUR),
    DATE_SUB(NOW(), INTERVAL 29 HOUR),
    DATE_SUB(NOW(), INTERVAL 29 HOUR),
    NULL,
    '',
    NULL,
    'TXN_PKG_SUCCESS_002'
  ),
  (
    'pkg_order_seed_005',
    'LDPKG20260419005',
    'user_pkg_seed_005',
    2,
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'join',
    NULL,
    64000,
    'success',
    DATE_SUB(NOW(), INTERVAL 24 HOUR),
    DATE_SUB(NOW(), INTERVAL 23 HOUR),
    DATE_SUB(NOW(), INTERVAL 23 HOUR),
    NULL,
    '',
    NULL,
    'TXN_PKG_SUCCESS_003'
  ),
  (
    'pkg_order_seed_006',
    'LDPKG20260419006',
    'user_pkg_seed_006',
    2,
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'join',
    NULL,
    64000,
    'success',
    DATE_SUB(NOW(), INTERVAL 20 HOUR),
    DATE_SUB(NOW(), INTERVAL 19 HOUR),
    DATE_SUB(NOW(), INTERVAL 19 HOUR),
    NULL,
    '',
    NULL,
    'TXN_PKG_SUCCESS_004'
  ),
  (
    'pkg_order_seed_007',
    'LDPKG20260419007',
    'user_pkg_seed_005',
    2,
    NULL,
    NULL,
    'package_seed_failed_004',
    'pkg_group_seed_003',
    'start',
    '{\"targetCount\":4,\"weekday\":7,\"hour\":9}',
    42200,
    'refunded',
    DATE_SUB(NOW(), INTERVAL 72 HOUR),
    DATE_SUB(NOW(), INTERVAL 1 HOUR),
    DATE_SUB(NOW(), INTERVAL 71 HOUR),
    DATE_SUB(NOW(), INTERVAL 1 HOUR),
    '报名截止前未成团，系统自动退款',
    NULL,
    'TXN_PKG_FAILED_001'
  ),
  (
    'pkg_order_seed_008',
    'LDPKG20260419008',
    'user_pkg_seed_006',
    2,
    NULL,
    NULL,
    'package_seed_failed_004',
    'pkg_group_seed_003',
    'join',
    NULL,
    42200,
    'refunded',
    DATE_SUB(NOW(), INTERVAL 60 HOUR),
    DATE_SUB(NOW(), INTERVAL 1 HOUR),
    DATE_SUB(NOW(), INTERVAL 59 HOUR),
    DATE_SUB(NOW(), INTERVAL 1 HOUR),
    '报名截止前未成团，系统自动退款',
    NULL,
    'TXN_PKG_FAILED_002'
  );

INSERT INTO `payment_records` (
  id,
  order_id,
  user_id,
  course_id,
  group_id,
  package_id,
  package_group_id,
  provider,
  channel,
  payment_mode,
  out_trade_no,
  transaction_id,
  amount,
  status,
  callback_status,
  prepare_payload,
  callback_payload,
  paid_at,
  closed_at,
  created_at,
  updated_at
) VALUES
  (
    'pkg_pay_seed_001',
    'pkg_order_seed_001',
    'user_pkg_seed_001',
    NULL,
    NULL,
    'package_seed_active_002',
    'pkg_group_seed_001',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419001',
    'TXN_PKG_ACTIVE_001',
    49500,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_001\",\"packageId\":\"package_seed_active_002\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 17 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 18 HOUR),
    DATE_SUB(NOW(), INTERVAL 17 HOUR)
  ),
  (
    'pkg_pay_seed_002',
    'pkg_order_seed_002',
    'user_pkg_seed_002',
    NULL,
    NULL,
    'package_seed_active_002',
    'pkg_group_seed_001',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419002',
    'TXN_PKG_ACTIVE_002',
    49500,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_002\",\"packageId\":\"package_seed_active_002\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 11 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 12 HOUR),
    DATE_SUB(NOW(), INTERVAL 11 HOUR)
  ),
  (
    'pkg_pay_seed_003',
    'pkg_order_seed_003',
    'user_pkg_seed_003',
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419003',
    'TXN_PKG_SUCCESS_001',
    64000,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_003\",\"packageId\":\"package_seed_success_003\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 35 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 36 HOUR),
    DATE_SUB(NOW(), INTERVAL 35 HOUR)
  ),
  (
    'pkg_pay_seed_004',
    'pkg_order_seed_004',
    'user_pkg_seed_004',
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419004',
    'TXN_PKG_SUCCESS_002',
    64000,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_004\",\"packageId\":\"package_seed_success_003\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 29 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 30 HOUR),
    DATE_SUB(NOW(), INTERVAL 29 HOUR)
  ),
  (
    'pkg_pay_seed_005',
    'pkg_order_seed_005',
    'user_pkg_seed_005',
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419005',
    'TXN_PKG_SUCCESS_003',
    64000,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_005\",\"packageId\":\"package_seed_success_003\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 23 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 24 HOUR),
    DATE_SUB(NOW(), INTERVAL 23 HOUR)
  ),
  (
    'pkg_pay_seed_006',
    'pkg_order_seed_006',
    'user_pkg_seed_006',
    NULL,
    NULL,
    'package_seed_success_003',
    'pkg_group_seed_002',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419006',
    'TXN_PKG_SUCCESS_004',
    64000,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_006\",\"packageId\":\"package_seed_success_003\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 19 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 20 HOUR),
    DATE_SUB(NOW(), INTERVAL 19 HOUR)
  ),
  (
    'pkg_pay_seed_007',
    'pkg_order_seed_007',
    'user_pkg_seed_005',
    NULL,
    NULL,
    'package_seed_failed_004',
    'pkg_group_seed_003',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419007',
    'TXN_PKG_FAILED_001',
    42200,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_007\",\"packageId\":\"package_seed_failed_004\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 71 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 72 HOUR),
    DATE_SUB(NOW(), INTERVAL 1 HOUR)
  ),
  (
    'pkg_pay_seed_008',
    'pkg_order_seed_008',
    'user_pkg_seed_006',
    NULL,
    NULL,
    'package_seed_failed_004',
    'pkg_group_seed_003',
    'wechat',
    'mini_program',
    'mock',
    'LDPKG20260419008',
    'TXN_PKG_FAILED_002',
    42200,
    'paid',
    'MOCK_SUCCESS',
    '{\"orderId\":\"pkg_order_seed_008\",\"packageId\":\"package_seed_failed_004\"}',
    '{\"source\":\"seed\"}',
    DATE_SUB(NOW(), INTERVAL 59 HOUR),
    NULL,
    DATE_SUB(NOW(), INTERVAL 60 HOUR),
    DATE_SUB(NOW(), INTERVAL 1 HOUR)
  )
ON DUPLICATE KEY UPDATE
  user_id = VALUES(user_id),
  course_id = VALUES(course_id),
  group_id = VALUES(group_id),
  package_id = VALUES(package_id),
  package_group_id = VALUES(package_group_id),
  transaction_id = VALUES(transaction_id),
  amount = VALUES(amount),
  status = VALUES(status),
  callback_status = VALUES(callback_status),
  prepare_payload = VALUES(prepare_payload),
  callback_payload = VALUES(callback_payload),
  paid_at = VALUES(paid_at),
  closed_at = VALUES(closed_at),
  updated_at = VALUES(updated_at);
