INSERT INTO courses (
  id,
  name,
  course_category,
  cover,
  images,
  description,
  age_limit,
  address,
  location_district,
  location_community,
  location_detail,
  longitude,
  latitude,
  group_price,
  original_price,
  publish_time,
  unpublish_time,
  deadline,
  start_time,
  end_time,
  default_target_count,
  max_groups,
  status,
  coach_name,
  coach_intro,
  coach_certificates,
  rules,
  insurance_desc,
  service_qr_code,
  created_at,
  updated_at,
  created_by,
  updated_by
) VALUES (
  'course_release_seed_001',
  '体验课｜深圳南山少儿体适能',
  '体适能',
  'https://dummyimage.com/960x540/e8f4ff/21598a.png&text=Lindong+Course',
  '[\"https://dummyimage.com/1280x720/e8f4ff/21598a.png&text=Lindong+Course+01\",\"https://dummyimage.com/1280x720/d5ebff/21598a.png&text=Lindong+Course+02\"]',
  '<p>这是一门用于真实 CloudBase 环境联调的体验课，当前用于验证课程列表、课程详情、创建订单与支付准备链路。</p>',
  '4-7岁',
  '深圳市南山区科技园邻动训练点',
  '南山区',
  '科技园社区',
  '科技园邻动训练点 A 场',
  113.9512,
  22.5431,
  88,
  168,
  '2026-04-16 09:00:00',
  NULL,
  '2026-04-25 20:00:00',
  '2026-04-26 10:00:00',
  '2026-04-26 12:00:00',
  2,
  3,
  1,
  '林动教练',
  '用于真实环境联调的课程种子数据。',
  '[\"https://dummyimage.com/480x320/e8f4ff/21598a.png&text=Coach+Cert\"]',
  '开课前请提前 10 分钟到场；如未成团将自动退款。',
  '本课程含基础运动意外险。',
  'https://dummyimage.com/240x240/f3f8ff/1677ff.png&text=%E5%AE%A2%E6%9C%8D',
  '2026-04-18 10:00:00',
  '2026-04-18 10:00:00',
  NULL,
  NULL
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  course_category = VALUES(course_category),
  cover = VALUES(cover),
  images = VALUES(images),
  description = VALUES(description),
  age_limit = VALUES(age_limit),
  address = VALUES(address),
  location_district = VALUES(location_district),
  location_community = VALUES(location_community),
  location_detail = VALUES(location_detail),
  longitude = VALUES(longitude),
  latitude = VALUES(latitude),
  group_price = VALUES(group_price),
  original_price = VALUES(original_price),
  publish_time = VALUES(publish_time),
  unpublish_time = VALUES(unpublish_time),
  deadline = VALUES(deadline),
  start_time = VALUES(start_time),
  end_time = VALUES(end_time),
  default_target_count = VALUES(default_target_count),
  max_groups = VALUES(max_groups),
  status = VALUES(status),
  coach_name = VALUES(coach_name),
  coach_intro = VALUES(coach_intro),
  coach_certificates = VALUES(coach_certificates),
  rules = VALUES(rules),
  insurance_desc = VALUES(insurance_desc),
  service_qr_code = VALUES(service_qr_code),
  updated_at = VALUES(updated_at);
