const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const appJsonPath = path.resolve(__dirname, '..', 'app.json')
const detailJsPath = path.resolve(__dirname, '..', 'pages/course/detail/index.js')
const detailWxmlPath = path.resolve(__dirname, '..', 'pages/course/detail/index.wxml')
const detailJsonPath = path.resolve(__dirname, '..', 'pages/course/detail/index.json')
const groupDetailWxmlPath = path.resolve(__dirname, '..', 'pages/group/detail/index.wxml')
const groupDetailJsonPath = path.resolve(__dirname, '..', 'pages/group/detail/index.json')
const courseOverviewComponentWxmlPath = path.resolve(__dirname, '..', 'components/course-overview-sections/index.wxml')
const insuranceBannerComponentJsPath = path.resolve(__dirname, '..', 'components/insurance-banner/index.js')
const insuranceBannerComponentWxmlPath = path.resolve(__dirname, '..', 'components/insurance-banner/index.wxml')
const insurancePageJsPath = path.resolve(__dirname, '..', 'pages/insurance/intro/index.js')
const insurancePageWxmlPath = path.resolve(__dirname, '..', 'pages/insurance/intro/index.wxml')

test('course detail and group detail reuse the shared overview components', () => {
  const jsSource = fs.readFileSync(detailJsPath, 'utf8')
  const wxmlSource = fs.readFileSync(detailWxmlPath, 'utf8')
  const detailJsonSource = fs.readFileSync(detailJsonPath, 'utf8')
  const groupDetailWxmlSource = fs.readFileSync(groupDetailWxmlPath, 'utf8')
  const groupDetailJsonSource = fs.readFileSync(groupDetailJsonPath, 'utf8')
  const courseOverviewWxmlSource = fs.readFileSync(courseOverviewComponentWxmlPath, 'utf8')
  const componentJsSource = fs.readFileSync(insuranceBannerComponentJsPath, 'utf8')
  const componentWxmlSource = fs.readFileSync(insuranceBannerComponentWxmlPath, 'utf8')

  assert.doesNotMatch(jsSource, /handleOpenInsuranceIntro\(\)/)
  assert.match(detailJsonSource, /"course-overview-sections": "\.\.\/\.\.\/\.\.\/components\/course-overview-sections\/index"/)
  assert.match(groupDetailJsonSource, /"course-overview-sections": "\.\.\/\.\.\/\.\.\/components\/course-overview-sections\/index"/)
  assert.match(componentJsSource, /url:\s*'\/pages\/insurance\/intro\/index'/)
  assert.match(componentWxmlSource, /course-insurance-banner\.png/)
  assert.match(courseOverviewWxmlSource, /insurance-banner/)
  assert.match(courseOverviewWxmlSource, /课程介绍/)
  assert.match(courseOverviewWxmlSource, /教练信息/)
  assert.match(wxmlSource, /<course-overview-sections/)
  assert.match(groupDetailWxmlSource, /<course-overview-sections/)
})

test('insurance intro page is registered and contains policy sections', () => {
  const appJsonSource = fs.readFileSync(appJsonPath, 'utf8')
  const jsSource = fs.readFileSync(insurancePageJsPath, 'utf8')
  const wxmlSource = fs.readFileSync(insurancePageWxmlPath, 'utf8')

  assert.match(appJsonSource, /pages\/insurance\/intro\/index/)
  assert.match(jsSource, /平安行·运动意外险（基础版）/)
  assert.doesNotMatch(jsSource, /为增强对学生的保障，课程包含本运动意外险/)
  assert.match(jsSource, /为保护学员和家长的隐私/)
  assert.match(jsSource, /保单生效后/)
  assert.doesNotMatch(jsSource, /保单成效后/)
  assert.match(jsSource, /平安好生活/)
  assert.match(wxmlSource, /brand-logo/)
  assert.match(wxmlSource, /pingan-logo\.svg/)
  assert.match(wxmlSource, /保障计划一览/)
  assert.match(wxmlSource, /保障责任详解/)
})
