const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const startJsPath = path.resolve(__dirname, '..', 'pages/package/start/index.js')
const startWxmlPath = path.resolve(__dirname, '..', 'pages/package/start/index.wxml')

test('package start page tracks frequency schedule state for multi-session packages', () => {
  const source = fs.readFileSync(startJsPath, 'utf8')

  assert.match(source, /classDurationMinutes/)
  assert.match(source, /buildSelectableScheduleDates/)
  assert.match(source, /buildTimeOptions/)
  assert.match(source, /scheduleTypeOptions/)
  assert.match(source, /selectedScheduleTypeValue/)
  assert.match(source, /selectedScheduleTime:\s*''/)
  assert.match(source, /selectedScheduleTimeLabel:\s*EMPTY_SCHEDULE_TEXT/)
  assert.match(source, /selectedTimeIndex:\s*-1/)
  assert.match(source, /selectedScheduleDays/)
  assert.match(source, /pendingScheduleDays/)
  assert.match(source, /scheduleDaysDisplayText/)
  assert.match(source, /openScheduleDaysPopup/)
  assert.match(source, /confirmScheduleDaysPopup/)
  assert.match(source, /editableScheduleList/)
  assert.match(source, /openScheduleItemEditor/)
  assert.match(source, /confirmScheduleItemEditor/)
  assert.match(source, /editingScheduleDateOptions/)
  assert.match(source, /editingScheduleDateIndex/)
  assert.match(source, /handleScheduleItemPickerChange/)
  assert.doesNotMatch(source, /handleScheduleItemDateChange/)
  assert.doesNotMatch(source, /handleScheduleItemTimeChange/)
  assert.match(source, /editingScheduleItemEndTime/)
  assert.match(source, /classDurationMinutes/)
  assert.match(source, /需选择\$\{weeklyTimes\}天/)
  assert.match(source, /上课时间不可重复/)
  assert.match(source, /schedulePreviewList/)
  assert.match(source, /formatPreviewDisplayText\(classTime, endTime\)/)
  assert.doesNotMatch(source, /item\.displayText \|\| formatPreviewDisplayText/)
})

test('package start page renders frequency choices and weekly multi-select UI', () => {
  const source = fs.readFileSync(startWxmlPath, 'utf8')
  const styleSource = fs.readFileSync(path.resolve(__dirname, '..', 'pages/package/start/index.wxss'), 'utf8')

  assert.doesNotMatch(source, /课程频率/)
  assert.doesNotMatch(source, /selectedScheduleTypeValue\.indexOf\('weekly'\)/)
  assert.match(source, /schedule-type-grid/)
  assert.match(source, /上课日期/)
  assert.doesNotMatch(source, /开始日期/)
  assert.match(source, /openScheduleDaysPopup/)
  assert.match(source, /schedule-sheet/)
  assert.match(source, /选择上课日期/)
  assert.match(source, /需选择\{\{requiredScheduleDaysCount\}\}天/)
  assert.match(source, /weekday-chip-grid--sheet/)
  assert.match(source, /请选择/)
  assert.doesNotMatch(source, /start-form-arrow/)
  assert.match(source, /wx:if="\{\{classCount > 1\}\}"/)
  assert.match(source, /课时预览/)
  assert.match(source, /bindtap="openScheduleItemEditor"/)
  assert.match(source, /schedule-preview-arrow/)
  assert.match(source, /schedule-item-editor-sheet/)
  assert.match(source, /选择上课时间/)
  assert.match(source, /上课时间/)
  assert.match(source, /picker-view/)
  assert.match(source, /picker-view-column/)
  assert.match(source, /editingScheduleDateOptions/)
  assert.doesNotMatch(source, /结束时间/)
  assert.doesNotMatch(source, /schedule-item-editor-row--current/)
  assert.doesNotMatch(source, /bindchange="handleScheduleItemDateChange"/)
  assert.doesNotMatch(source, /bindchange="handleScheduleItemTimeChange"/)
  assert.match(styleSource, /height:\s*112rpx;/)
  assert.doesNotMatch(styleSource, /schedule-item-editor-picker-item[\s\S]*min-height:\s*112rpx;/)
  assert.match(styleSource, /schedule-preview-arrow/)
  assert.match(styleSource, /schedule-preview-text[\s\S]*color:\s*#111827;/)
  assert.doesNotMatch(styleSource, /start-form-arrow/)
})

test('package start page exposes explicit weekly render state instead of template method calls', () => {
  const source = fs.readFileSync(startJsPath, 'utf8')

  assert.match(source, /isWeeklySchedule/)
})
